Repository migpalg/colors, pull requests merged in 2020-03, with the labels that each got.

#12 Added backgrounds
  src/css/main.css
  src/img/bgs/home.png
  src/img/bgs/splash.png
Labels: feature

#13 Added gems assets
  src/img/gems/circle/blue.svg
  src/img/gems/circle/crimson.svg
  src/img/gems/circle/darkblue.svg
  src/img/gems/circle/green.svg
  src/img/gems/circle/purple.svg
  src/img/gems/circle/yellow.svg
  src/img/gems/diamond/blue.svg
  src/img/gems/diamond/crimson.svg
  src/img/gems/diamond/darkblue.svg
  src/img/gems/diamond/green.svg
  src/img/gems/diamond/purple.svg
  src/img/gems/diamond/yellow.svg
  src/img/gems/oval/blue.svg
  src/img/gems/oval/crimson.svg
  src/img/gems/oval/darkblue.svg
  src/img/gems/oval/green.svg
  src/img/gems/oval/purple.svg
  src/img/gems/oval/yellow.svg
  src/img/gems/rhombus/blue.svg
  src/img/gems/rhombus/crimson.svg
  src/img/gems/rhombus/darkblue.svg
  src/img/gems/rhombus/green.svg
  src/img/gems/rhombus/purole.svg
  src/img/gems/rhombus/yellow.svg
  src/img/gems/square/blue.svg
  src/img/gems/square/crimson.svg
  src/img/gems/square/darkblue.svg
  src/img/gems/square/green.svg
  src/img/gems/square/purple.svg
  src/img/gems/square/yellow.svg
  src/img/gems/triangle/blue.svg
  src/img/gems/triangle/crimson.svg
  src/img/gems/triangle/darkblue.svg
  src/img/gems/triangle/green.svg
  src/img/gems/triangle/purple.svg
  src/img/gems/triangle/yellow.svg
Labels: feature

#18 Features/buttons
  src/css/main.css
  src/img/navigation/credits.png
  src/img/navigation/play.png
  src/img/navigation/stats.png
  src/img/navigation/tutorial.png
  src/index.html
Labels: feature

#19 Feature/difficult screen design
  src/css/main.css
  src/img/navigation/easy.png
  src/img/navigation/hard.png
  src/img/navigation/medium.png
  src/index.html
  src/js/main.js
Labels: feature

#21 Features/review grid
  src/css/main.css
  src/img/bgs/papelpuntos.png
  src/img/gems/gems.svg
  src/img/navigation/volverajugar.png
  src/index.html
  src/js/main.js
Labels: feature

#20 Implemented game screen
  src/css/main.css
  src/img/gems/stone-background-01.png
  src/img/gems/stone-background-02.png
  src/img/time-leaf.png
  src/index.html
  src/js/main.js
Labels: feature

#22 Features/tiny png
  src/img/app-logo.png
  src/img/authors/juan-pablo.jpg
  src/img/authors/maria-isabel.jpg
  src/img/authors/miguel-angel.jpg
  src/img/bgs/default.png
  src/img/bgs/home.png
  src/img/bgs/papelpuntos.png
  src/img/bgs/splash.png
  src/img/gems/stone-background-01.png
  src/img/gems/stone-background-02.png
  src/img/navigation/close.png
  src/img/navigation/credits.png
  src/img/navigation/easy.png
  src/img/navigation/hard.png
  src/img/navigation/medium.png
  src/img/navigation/play.png
  src/img/navigation/stats.png
  src/img/navigation/tutorial.png
  src/img/navigation/volverajugar.png
  src/img/time-leaf.png
Labels: feature, good first issue

#23 Pantalla de historial de estadísticas
  src/css/main.css
  src/img/stats-positions/1.png
  src/img/stats-positions/2.png
  src/img/stats-positions/3.png
  src/index.html
  src/js/main.js
Labels: feature

#24 Gema changed to Figura
  src/js/main.js
Labels: bug

#25 Añadido div para corregir el layout
  src/css/main.css
  src/index.html
Labels: bug

#27 Fixed Grunt uglify error
  Gruntfile.js
  src/js/main.js
Labels: bug

#28 Actualizadas las dependencias del proyecto
  package-lock.json
  package.json
Labels: enhancement, feature

#30 Added background
  src/css/main.css
  src/img/bgs/fondo.png
  src/index.html
Labels: feature
