Repository migpalg/colors, pull requests merged in 2020-02, with the labels that each got.

#1 Fixed inline elements
  src/css/styles.css
  src/js/app.js
Labels: bug

#2 History screen
  src/index.html
  src/js/app.js
Labels: enhancement

#3 Implemented game history stats
  src/index.html
  src/js/app.js
Labels: enhancement, feature

#4 Added splash
  src/css/styles.css
  src/img/app-logo.png
  src/index.html
Labels: feature

#5 Cambio de nombre de los archivos, configuración grunt
  Gruntfile.js
  package-lock.json
  package.json
  src/css/main.css
  src/index.html
  src/js/main.js
Labels: feature

#8 Se añado el font-family principal
  src/css/main.css
  src/fonts/KGBlankSpaceSolid.ttf
Labels: feature

#9 Added fonts copy on grunt
  Gruntfile.js
Labels: enhancement, feature

#10 Correciones varias, ajuste de estilos a el font principal y logo
  src/css/main.css
  src/index.html
  src/js/main.js
Labels: feature
